apiVersion: v1
kind: Pod
metadata:
        name: webserver
        labels:
                app: webapp
                type: frontend
spec:
        containers:
                - name: xyz
                  image: wordpress
                  envFrom:
                          - configMapRef:
                                  name: wordpress

