apiVersion: v1
kind: Pod
metadata:
        name: deepak
        labels:
                env: test
spec:
        containers:
                - name: webserver
                  image: centos/httpd
        tolerations:
                - key: "app"
                  operator: "Equal"
                  value: "database"
                  effect: "NoSchedule"
